#include <string>
#include "RawData.h"

string RawData::INPUT_DATA_RAW_EXAMPLE =
        "$ cd /\n"
        "$ ls\n"
        "dir a\n"
        "14848514 b.txt\n"
        "8504156 c.dat\n"
        "dir d\n"
        "$ cd a\n"
        "$ ls\n"
        "dir e\n"
        "29116 f\n"
        "2557 g\n"
        "62596 h.lst\n"
        "$ cd e\n"
        "$ ls\n"
        "584 i\n"
        "$ cd ..\n"
        "$ cd ..\n"
        "$ cd d\n"
        "$ ls\n"
        "4060174 j\n"
        "8033020 d.log\n"
        "5626152 d.ext\n"
        "7214296 k";

string RawData::INPUT_DATA_RAW =
	"$ cd /\n"
    "$ ls\n"
    "dir bfqzjjct\n"
    "dir cgcqpjpn\n"
    "dir frrjh\n"
    "dir jjl\n"
    "293559 jztrccm.hvd\n"
    "dir mqvn\n"
    "$ cd bfqzjjct\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "dir frrjh\n"
    "dir gzpbchq\n"
    "12679 lzrgqrgc\n"
    "dir mzm\n"
    "dir phslrcw\n"
    "240839 phslrcw.ljl\n"
    "dir qftq\n"
    "dir qlpg\n"
    "169962 vntqgq.tps\n"
    "114950 vzq.qvv\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "305598 hjrv\n"
    "134990 jlqcf.sjc\n"
    "dir phslrcw\n"
    "dir qsdlvr\n"
    "129733 rznmd.snf\n"
    "dir sgcg\n"
    "dir swfsblvv\n"
    "dir vprjf\n"
    "dir wchtzbdv\n"
    "dir wfvj\n"
    "229649 zdm.rpl\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir jnzjq\n"
    "dir lfd\n"
    "79014 lzrgqrgc.sqh\n"
    "209222 wfnmqrtr.zbq\n"
    "$ cd jnzjq\n"
    "$ ls\n"
    "163133 qsdcrvz.zmn\n"
    "287008 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd lfd\n"
    "$ ls\n"
    "4442 cgcqpjpn\n"
    "61281 jmr\n"
    "212696 jztrccm.hvd\n"
    "dir mlt\n"
    "dir qsdlvr\n"
    "$ cd mlt\n"
    "$ ls\n"
    "183050 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "dir nzjfwdt\n"
    "dir qsdlvr\n"
    "$ cd nzjfwdt\n"
    "$ ls\n"
    "49044 jdqz.bqd\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "13838 fpfmhq.rbp\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "167042 jdqz.bqd\n"
    "132914 lzrgqrgc\n"
    "$ cd ..\n"
    "$ cd sgcg\n"
    "$ ls\n"
    "dir bjwzfr\n"
    "111567 jdqz.bqd\n"
    "33253 jztrccm.hvd\n"
    "75760 qsdlvr\n"
    "$ cd bjwzfr\n"
    "$ ls\n"
    "268763 npjd.glz\n"
    "dir phslrcw\n"
    "121486 vbfsrwf.mbc\n"
    "dir vtwtmnvl\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "114641 cgsrlq\n"
    "235130 npjd.glz\n"
    "$ cd ..\n"
    "$ cd vtwtmnvl\n"
    "$ ls\n"
    "7771 hnrpgsn\n"
    "290862 rtrljz.vbf\n"
    "220102 rztn.vqq\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd swfsblvv\n"
    "$ ls\n"
    "231282 vclmcf.vpq\n"
    "16727 vjhmb.ftn\n"
    "$ cd ..\n"
    "$ cd vprjf\n"
    "$ ls\n"
    "dir fppsf\n"
    "56173 npjd.glz\n"
    "dir phslrcw\n"
    "dir pwjdcdff\n"
    "dir qsdlvr\n"
    "dir qvh\n"
    "dir sbmtlz\n"
    "$ cd fppsf\n"
    "$ ls\n"
    "dir hltnf\n"
    "dir qrmggjs\n"
    "dir qsdlvr\n"
    "$ cd hltnf\n"
    "$ ls\n"
    "201448 npjd.glz\n"
    "23616 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd qrmggjs\n"
    "$ ls\n"
    "dir blhwqwd\n"
    "dir szf\n"
    "$ cd blhwqwd\n"
    "$ ls\n"
    "142887 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd szf\n"
    "$ ls\n"
    "225491 tvsf.tpv\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "92209 brmrwznr\n"
    "dir frrjh\n"
    "212979 qsdlvr.bwh\n"
    "dir vpvnb\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "143811 qvwmpj.gnc\n"
    "$ cd ..\n"
    "$ cd vpvnb\n"
    "$ ls\n"
    "dir wwsw\n"
    "$ cd wwsw\n"
    "$ ls\n"
    "13671 qsdlvr\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir bpfhc\n"
    "dir fjvgwbj\n"
    "127950 hjngrw.rtr\n"
    "37045 lfpjb.ftz\n"
    "dir qsn\n"
    "$ cd bpfhc\n"
    "$ ls\n"
    "232351 frrjh.szf\n"
    "14824 jztrccm.hvd\n"
    "162270 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd fjvgwbj\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "4290 jrfsmghw.vqr\n"
    "dir lqnpdd\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "208104 btrcq.vpn\n"
    "149676 bwvp.jlf\n"
    "76056 gvvrvqdf.zdc\n"
    "272686 pqhtjpv\n"
    "dir zjntbw\n"
    "$ cd zjntbw\n"
    "$ ls\n"
    "140092 jdqz.bqd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd lqnpdd\n"
    "$ ls\n"
    "dir brf\n"
    "197899 jdqz.bqd\n"
    "dir phslrcw\n"
    "236823 qcvgnlv.ngn\n"
    "dir szrfcwtw\n"
    "88974 vzq.qvv\n"
    "$ cd brf\n"
    "$ ls\n"
    "112059 jdqz.bqd\n"
    "217412 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "84285 jnzf\n"
    "282660 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd szrfcwtw\n"
    "$ ls\n"
    "84415 gcp\n"
    "163787 wffb.wbq\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsn\n"
    "$ ls\n"
    "139676 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd pwjdcdff\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "54163 lzrgqrgc\n"
    "dir qsdlvr\n"
    "51246 qsdlvr.cmq\n"
    "5082 rvmv.tqj\n"
    "112712 vzq.qvv\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "92895 dmf.bsv\n"
    "dir lhqzc\n"
    "$ cd lhqzc\n"
    "$ ls\n"
    "13443 hwlsmmjn.wpj\n"
    "232141 tlsn\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "216144 dghbz.lnl\n"
    "241311 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "109764 qsdlvr.tbj\n"
    "$ cd ..\n"
    "$ cd qvh\n"
    "$ ls\n"
    "dir frrjh\n"
    "51428 hdtmm.zzl\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "271661 brff.mgp\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd sbmtlz\n"
    "$ ls\n"
    "277255 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd wchtzbdv\n"
    "$ ls\n"
    "198310 cgcqpjpn\n"
    "300478 fcfvgpdr.lzv\n"
    "145860 jdqz.bqd\n"
    "20145 mggg\n"
    "$ cd ..\n"
    "$ cd wfvj\n"
    "$ ls\n"
    "270522 phslrcw.mwt\n"
    "213919 tczvr\n"
    "19226 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "246391 hnc.bzl\n"
    "dir lzrgqrgc\n"
    "dir mnrbzwr\n"
    "239337 npjd.glz\n"
    "dir qsdlvr\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "2423 pflhrgjg.gch\n"
    "$ cd ..\n"
    "$ cd lzrgqrgc\n"
    "$ ls\n"
    "265708 vzq.qvv\n"
    "107406 zwnjb\n"
    "$ cd ..\n"
    "$ cd mnrbzwr\n"
    "$ ls\n"
    "287289 jgs.bdb\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "dir qsdlvr\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "71204 gnfz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd gzpbchq\n"
    "$ ls\n"
    "dir cmqgph\n"
    "dir fwf\n"
    "146975 jztrccm.hvd\n"
    "284515 lzrgqrgc.qsf\n"
    "27455 qbsbvscc\n"
    "$ cd cmqgph\n"
    "$ ls\n"
    "177740 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd fwf\n"
    "$ ls\n"
    "210658 dnmvdgwn.wzt\n"
    "22013 rqcspw.qmf\n"
    "244013 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd mzm\n"
    "$ ls\n"
    "262805 gnfsbdcd.tvp\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "74949 wncqjc.tzd\n"
    "$ cd ..\n"
    "$ cd qftq\n"
    "$ ls\n"
    "dir jrds\n"
    "$ cd jrds\n"
    "$ ls\n"
    "dir dvht\n"
    "dir qsdlvr\n"
    "$ cd dvht\n"
    "$ ls\n"
    "57354 phslrcw\n"
    "57174 qsdlvr.ftm\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "132030 fbsmfspp\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qlpg\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "dir frrjh\n"
    "dir jjsfmg\n"
    "186178 jmvcvw\n"
    "dir qgjhlnmf\n"
    "100234 qltp.vdr\n"
    "dir tbwt\n"
    "dir vjjvfbdw\n"
    "dir wjz\n"
    "162428 zlbnsg\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "dir gvmgcftp\n"
    "dir hsgvgc\n"
    "dir nps\n"
    "dir phslrcw\n"
    "dir scdglb\n"
    "$ cd gvmgcftp\n"
    "$ ls\n"
    "31869 dsddwbbp\n"
    "dir fbsrjgzj\n"
    "53280 tzn.fvp\n"
    "$ cd fbsrjgzj\n"
    "$ ls\n"
    "89267 qsdlvr.lhs\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd hsgvgc\n"
    "$ ls\n"
    "dir lzrgqrgc\n"
    "210774 wpspf.vrd\n"
    "$ cd lzrgqrgc\n"
    "$ ls\n"
    "289086 gfhwwslq.tlz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd nps\n"
    "$ ls\n"
    "74713 fnqzcr\n"
    "dir srjvfq\n"
    "94736 wbrcn.nng\n"
    "dir wmddln\n"
    "dir zsgnrmcc\n"
    "$ cd srjvfq\n"
    "$ ls\n"
    "dir grqft\n"
    "dir pjnjlf\n"
    "254618 wmfnmfrc.wng\n"
    "$ cd grqft\n"
    "$ ls\n"
    "3742 zmpzwh.nvz\n"
    "$ cd ..\n"
    "$ cd pjnjlf\n"
    "$ ls\n"
    "dir mlrsrs\n"
    "$ cd mlrsrs\n"
    "$ ls\n"
    "167149 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd wmddln\n"
    "$ ls\n"
    "222831 cgcqpjpn.dcv\n"
    "140188 gsvngqp\n"
    "174466 sfngrqgj.gvz\n"
    "$ cd ..\n"
    "$ cd zsgnrmcc\n"
    "$ ls\n"
    "143043 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir cdfsrvnc\n"
    "103523 hzsjc\n"
    "239089 jvwdjbq\n"
    "229835 npjd.glz\n"
    "189778 wwcccwmb.bdp\n"
    "$ cd cdfsrvnc\n"
    "$ ls\n"
    "dir vzsvcnlz\n"
    "$ cd vzsvcnlz\n"
    "$ ls\n"
    "dir wwn\n"
    "$ cd wwn\n"
    "$ ls\n"
    "60279 frngbwm.wwf\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd scdglb\n"
    "$ ls\n"
    "176557 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "130811 jdqz.bqd\n"
    "$ cd ..\n"
    "$ cd jjsfmg\n"
    "$ ls\n"
    "dir nffq\n"
    "22842 vzt.nwh\n"
    "$ cd nffq\n"
    "$ ls\n"
    "dir wmq\n"
    "$ cd wmq\n"
    "$ ls\n"
    "196322 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qgjhlnmf\n"
    "$ ls\n"
    "dir jhqqjt\n"
    "dir phslrcw\n"
    "246296 pzvmcq\n"
    "219308 tlhqgtcl.twb\n"
    "dir vfgb\n"
    "300258 zdm.rpl\n"
    "221663 zsqh.dph\n"
    "$ cd jhqqjt\n"
    "$ ls\n"
    "90068 fctpjdlm.ggg\n"
    "dir frrjh\n"
    "dir ngmzbqb\n"
    "dir phslrcw\n"
    "64341 qsdlvr.pnq\n"
    "dir vlgpcg\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "49247 qrrhdhld.sjr\n"
    "$ cd ..\n"
    "$ cd ngmzbqb\n"
    "$ ls\n"
    "247800 cgcqpjpn.wgv\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir qsdlvr\n"
    "dir vjrrrm\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "255302 ddvc\n"
    "182817 dzd.trp\n"
    "$ cd ..\n"
    "$ cd vjrrrm\n"
    "$ ls\n"
    "38983 hjbsqd.pdl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd vlgpcg\n"
    "$ ls\n"
    "dir frrjh\n"
    "83387 jztrccm.hvd\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "dir rmlc\n"
    "$ cd rmlc\n"
    "$ ls\n"
    "273584 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "96286 jztrccm.hvd\n"
    "224425 npjd.glz\n"
    "$ cd ..\n"
    "$ cd vfgb\n"
    "$ ls\n"
    "dir fgl\n"
    "dir fllsgwjt\n"
    "dir frrjh\n"
    "dir qsdlvr\n"
    "$ cd fgl\n"
    "$ ls\n"
    "61972 lzrgqrgc.qrs\n"
    "$ cd ..\n"
    "$ cd fllsgwjt\n"
    "$ ls\n"
    "dir fqchdcpd\n"
    "214477 zcr.spz\n"
    "$ cd fqchdcpd\n"
    "$ ls\n"
    "156000 jccqlw.twl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "210987 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "dir phslrcw\n"
    "dir znnsfvz\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "214655 ddw\n"
    "$ cd ..\n"
    "$ cd znnsfvz\n"
    "$ ls\n"
    "126028 zpq.bgs\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd tbwt\n"
    "$ ls\n"
    "dir ltjjhr\n"
    "$ cd ltjjhr\n"
    "$ ls\n"
    "158069 vplwrz.rzp\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd vjjvfbdw\n"
    "$ ls\n"
    "277114 fmndb.rth\n"
    "241524 frrjh\n"
    "212152 frrjh.dlq\n"
    "61370 jztrccm.hvd\n"
    "dir srvqm\n"
    "237264 znt\n"
    "$ cd srvqm\n"
    "$ ls\n"
    "dir fbzmddc\n"
    "61958 jdqz.bqd\n"
    "dir phslrcw\n"
    "173063 vwvmhwzn.tvg\n"
    "$ cd fbzmddc\n"
    "$ ls\n"
    "dir ccvtbpzw\n"
    "201647 lzrgqrgc.sjs\n"
    "192449 rhfgcgz\n"
    "224557 sbcpcbpd\n"
    "$ cd ccvtbpzw\n"
    "$ ls\n"
    "dir phslrcw\n"
    "dir prpllzcn\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "290780 lbl.qmm\n"
    "$ cd ..\n"
    "$ cd prpllzcn\n"
    "$ ls\n"
    "242024 bhq\n"
    "118347 frrjh.tsz\n"
    "dir hcqs\n"
    "$ cd hcqs\n"
    "$ ls\n"
    "104706 csnllvcf\n"
    "270940 npjd.glz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "244909 czfjsrns.fdm\n"
    "dir frrjh\n"
    "68252 lzrgqrgc\n"
    "146640 npjd.glz\n"
    "290259 pbzpthgs.bgf\n"
    "99657 rmfpfmd\n"
    "dir zllf\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "65295 jdqz.bqd\n"
    "dir phslrcw\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "dir mwfwrd\n"
    "$ cd mwfwrd\n"
    "$ ls\n"
    "26481 sngtgc\n"
    "dir zfzddl\n"
    "$ cd zfzddl\n"
    "$ ls\n"
    "47854 fzfdrmbb.ngm\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "251021 fwfpd.vrt\n"
    "230149 fwjznjtz\n"
    "140480 gbsmhj\n"
    "112221 lzrgqrgc.gcr\n"
    "139564 npjd.glz\n"
    "dir pvmvm\n"
    "dir tpzr\n"
    "$ cd pvmvm\n"
    "$ ls\n"
    "73785 tnbgmgt.wqg\n"
    "$ cd ..\n"
    "$ cd tpzr\n"
    "$ ls\n"
    "16759 tmcmp\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd zllf\n"
    "$ ls\n"
    "281402 dzrsnzh.smb\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd wjz\n"
    "$ ls\n"
    "266826 cgcqpjpn.spr\n"
    "dir frvbfjj\n"
    "111126 jdqz.bqd\n"
    "257951 pbn.gdc\n"
    "dir vjs\n"
    "dir zrnvnb\n"
    "$ cd frvbfjj\n"
    "$ ls\n"
    "257181 glfdplrm\n"
    "$ cd ..\n"
    "$ cd vjs\n"
    "$ ls\n"
    "dir jmpbwhtj\n"
    "159996 lzrgqrgc.zcb\n"
    "192135 phw\n"
    "dir tdfz\n"
    "dir wtm\n"
    "$ cd jmpbwhtj\n"
    "$ ls\n"
    "dir fln\n"
    "dir frrjh\n"
    "dir nrtcmj\n"
    "$ cd fln\n"
    "$ ls\n"
    "284574 frrjh.scb\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "10020 npjd.glz\n"
    "295395 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd nrtcmj\n"
    "$ ls\n"
    "dir htvm\n"
    "$ cd htvm\n"
    "$ ls\n"
    "dir lwh\n"
    "$ cd lwh\n"
    "$ ls\n"
    "162494 npjd.glz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd tdfz\n"
    "$ ls\n"
    "dir gtvlbhhw\n"
    "dir hvssbj\n"
    "dir phslrcw\n"
    "$ cd gtvlbhhw\n"
    "$ ls\n"
    "172627 sjvcfz\n"
    "dir tfnhsrc\n"
    "76460 vvgcv\n"
    "$ cd tfnhsrc\n"
    "$ ls\n"
    "dir hjrjmrwc\n"
    "$ cd hjrjmrwc\n"
    "$ ls\n"
    "41459 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd hvssbj\n"
    "$ ls\n"
    "64052 phslrcw\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir wtdpf\n"
    "dir zctdqwbc\n"
    "$ cd wtdpf\n"
    "$ ls\n"
    "75802 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd zctdqwbc\n"
    "$ ls\n"
    "127648 vqzcf.wbl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd wtm\n"
    "$ ls\n"
    "265433 jztrccm.hvd\n"
    "20952 mplbrzlp\n"
    "123701 nwr.tjg\n"
    "58492 qsdlvr.qzq\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd zrnvnb\n"
    "$ ls\n"
    "228205 ghllsc.fqn\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "dir cmnsbsqp\n"
    "dir hzsn\n"
    "221975 jdqz.bqd\n"
    "177439 jztrccm.hvd\n"
    "dir mqjrcw\n"
    "dir tdp\n"
    "211065 zdm.rpl\n"
    "$ cd cmnsbsqp\n"
    "$ ls\n"
    "282903 qzlc\n"
    "$ cd ..\n"
    "$ cd hzsn\n"
    "$ ls\n"
    "221345 wtdnp.grd\n"
    "$ cd ..\n"
    "$ cd mqjrcw\n"
    "$ ls\n"
    "156244 gznmpr.dlr\n"
    "45213 hdb.fjb\n"
    "202993 pdt\n"
    "dir znvdz\n"
    "$ cd znvdz\n"
    "$ ls\n"
    "183973 jztrccm.hvd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd tdp\n"
    "$ ls\n"
    "68564 nmntwl\n"
    "259117 vzq.qvv\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "276034 lzrgqrgc.fgq\n"
    "dir psqczq\n"
    "dir qsdlvr\n"
    "dir snrw\n"
    "$ cd psqczq\n"
    "$ ls\n"
    "158415 jdqz.bqd\n"
    "127684 lhctqnnz.hgn\n"
    "123191 phslrcw.prl\n"
    "dir wrftp\n"
    "$ cd wrftp\n"
    "$ ls\n"
    "234327 qdbbl.czd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "179591 chbns.sqf\n"
    "88327 jdqz.bqd\n"
    "dir mrf\n"
    "$ cd mrf\n"
    "$ ls\n"
    "229849 phslrcw.rdr\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd snrw\n"
    "$ ls\n"
    "dir cbvr\n"
    "dir lbbrtc\n"
    "134786 lzrgqrgc.vrt\n"
    "131987 vzq.qvv\n"
    "$ cd cbvr\n"
    "$ ls\n"
    "120330 htmgqj.nbq\n"
    "162963 lzrgqrgc.rwq\n"
    "$ cd ..\n"
    "$ cd lbbrtc\n"
    "$ ls\n"
    "dir tnqdj\n"
    "$ cd tnqdj\n"
    "$ ls\n"
    "72261 lhqnwns.nhj\n"
    "235520 qsdlvr.dtr\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd jjl\n"
    "$ ls\n"
    "dir fcfpptw\n"
    "dir frrjh\n"
    "dir gmdwgs\n"
    "221258 jdqz.bqd\n"
    "dir lzrgqrgc\n"
    "dir mwnmjjj\n"
    "297139 smjtpl.zzs\n"
    "$ cd fcfpptw\n"
    "$ ls\n"
    "167264 frrjh\n"
    "101587 hsmhhc.lvb\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "268280 jztrccm.hvd\n"
    "127939 nbqgvd\n"
    "247875 nmnrsqq\n"
    "dir phslrcw\n"
    "dir rmgwbq\n"
    "288264 znrrdmw\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "dir cgcqpjpn\n"
    "dir nbwjw\n"
    "$ cd cgcqpjpn\n"
    "$ ls\n"
    "249503 phslrcw.dmf\n"
    "$ cd ..\n"
    "$ cd nbwjw\n"
    "$ ls\n"
    "dir phslrcw\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "193336 sqpgwtgp.fpb\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd rmgwbq\n"
    "$ ls\n"
    "90116 jztrccm.hvd\n"
    "303005 phslrcw\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd gmdwgs\n"
    "$ ls\n"
    "dir lzrgqrgc\n"
    "dir mwrj\n"
    "dir mzqn\n"
    "104570 qsqqbfg.njt\n"
    "dir zmj\n"
    "$ cd lzrgqrgc\n"
    "$ ls\n"
    "dir cmn\n"
    "dir qsdlvr\n"
    "dir rtz\n"
    "$ cd cmn\n"
    "$ ls\n"
    "20043 bgm.tvn\n"
    "41301 hqdl.rnr\n"
    "32026 tsmmr.bfl\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "dir dcsdmqt\n"
    "$ cd dcsdmqt\n"
    "$ ls\n"
    "107938 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd rtz\n"
    "$ ls\n"
    "308963 jbwvpjvj.fgn\n"
    "31573 jdqz.bqd\n"
    "97775 phslrcw\n"
    "dir qsdlvr\n"
    "225929 wwznl.bpd\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "52056 bddqnlmg.hjm\n"
    "236614 qsdlvr.vcz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd mwrj\n"
    "$ ls\n"
    "dir dfsm\n"
    "dir mtfqs\n"
    "$ cd dfsm\n"
    "$ ls\n"
    "32797 jztrccm.hvd\n"
    "dir mthjq\n"
    "241875 vzq.qvv\n"
    "$ cd mthjq\n"
    "$ ls\n"
    "147247 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd mtfqs\n"
    "$ ls\n"
    "dir crpfs\n"
    "dir phslrcw\n"
    "$ cd crpfs\n"
    "$ ls\n"
    "24073 jdqz.bqd\n"
    "269270 jztrccm.hvd\n"
    "89807 lzrgqrgc.ddj\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "124727 cgcqpjpn.zfz\n"
    "dir gttptlwj\n"
    "dir phslrcw\n"
    "dir qsdlvr\n"
    "$ cd gttptlwj\n"
    "$ ls\n"
    "295546 frrjh.tmq\n"
    "$ cd ..\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "234122 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "131491 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd mzqn\n"
    "$ ls\n"
    "16352 qjllmbh.jfm\n"
    "36853 zdm.rpl\n"
    "$ cd ..\n"
    "$ cd zmj\n"
    "$ ls\n"
    "dir dvrwbrbt\n"
    "dir frrjh\n"
    "217060 mftczjfs.zch\n"
    "dir znhsrsfb\n"
    "$ cd dvrwbrbt\n"
    "$ ls\n"
    "dir lzssrrq\n"
    "$ cd lzssrrq\n"
    "$ ls\n"
    "dir qsdlvr\n"
    "$ cd qsdlvr\n"
    "$ ls\n"
    "108975 npjd.glz\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd frrjh\n"
    "$ ls\n"
    "dir phslrcw\n"
    "dir zjstpvl\n"
    "$ cd phslrcw\n"
    "$ ls\n"
    "244682 pgn.jqm\n"
    "$ cd ..\n"
    "$ cd zjstpvl\n"
    "$ ls\n"
    "300736 bsw.wzn\n"
    "102742 jdqz.bqd\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd znhsrsfb\n"
    "$ ls\n"
    "121093 qsdlvr\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd lzrgqrgc\n"
    "$ ls\n"
    "50942 jdqz.bqd\n"
    "26201 ljqgqqrr\n"
    "71462 lrrfvs.ghl\n"
    "274208 tqhcl.hcl\n"
    "$ cd ..\n"
    "$ cd mwnmjjj\n"
    "$ ls\n"
    "184865 mzwmp.jbw\n"
    "68016 thbh.nbg\n"
    "$ cd ..\n"
    "$ cd ..\n"
    "$ cd mqvn\n"
    "$ ls\n"
    "287623 spfzctll";